version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Docker_go
    command: /bin/sh -c "cd /app && go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080